name: tetris
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: Khizar Ali <khizar.ali.manzoor@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  shelf: any
  shelf_static: any

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0
  firebase: ^7.1.0
